packages:
  - 'packages/*'

catalog:
  hono: 4.7.10
  wrangler: 4.17.0
  '@hono/swagger-ui': 0.5.1
  '@hono/trpc-server': 0.3.4
  '@trpc/server': 11.0.0-rc.833
  '@trpc/client': 11.0.0-rc.833
  '@trpc/react-query': 11.0.0-rc.833
  '@tanstack/react-query': 5.68.0
  zod: 3.24.2
  trpc-to-openapi: 2.1.3
  zod-openapi: 4.2.3
