packages:
  - 'packages/*'

catalog:
  '@cloudflare/workers-types': 4.20250523.0
  '@hono/swagger-ui': 0.5.1
  '@hono/trpc-server': 0.3.4
  '@tanstack/react-query': 5.68.0
  '@trpc/client': 11.1.3
  '@trpc/react-query': 11.1.3
  '@trpc/server': 11.1.3
  hono: 4.7.10
  trpc-to-openapi: 2.3.1
  typescript: 5.7.3
  wrangler: 4.15.2
  zod-openapi: 4.2.4
  zod: 3.24.2
